### ISSUE TITLE
add more pictures and/or links to social media

### ISSUE THREAD

**Issue by acra6488** [Charlie1qa/PerfecTea#13]
Hi, I really like the drawing/sketch of the project!
Whenever your PCBs are ready, it would be great to add some pictures of those, and of any testing you have. Perhaps on a social media page?
-Aurelie -Team 2

**Comment by Charlie1qa** [comment]
Hi,
We've uploaded some PDFs of our PCBs and some CAD files for the structure. We'll add these to our social media pages at a later date. 

Thanks.
