### ISSUE TITLE
Software Improvements etc.

### ISSUE THREAD

**Issue by 2077762b** [Charlie1qa/PerfecTea#9]
This project looks like it is progressing well. A few possible improvements include:
* Converting the C code to C++ so that it can make use of the object orientated paradigm.
* Appropriate commenting in the code such that it is easy to understand the purpose of each function.
* Adding PCB board files in addition to the schematic files which have been included.
* Meaningful commit message. Messages such as "fixed" are not helpful. Ideally they should explain which files have been edited and why.
* It would still be quite difficult to replicate the project without further instructions on assembling the mechanical structure.

**Team 10**

**Comment by Charlie1qa** [comment]
We will improve on our commenting and commit messages. The PCB board files/ artwork will be uploaded when completed. And more detailed files concerning the chassis will be uploaded.
